### ISSUE TITLE
Contact Us

### ISSUE THREAD

**Issue by ericwjr** [ericwjr/notice#13]
Instead of modal/dialog...Contact Us should be in the single page

**Comment by ericwjr** [comment]
Also use black as backdrop instead of green

**Comment by ericwjr** [comment]
This is good, lets remove "Choose subject" dropdown for now

**Comment by onweru** [comment]
Fixed

**Comment by ericwjr** [comment]
I still see drop down but now I like it (fonts matter lol).  Here are options:
Join e-mailed list
Offer a Suggestion
Partnership Opportunity Inquiry


_Sent from my LGE Nexus 5X using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
